INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (1, 'Esterilización canina');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (2, 'Castración felina');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (3, 'Extracción dental');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (4, 'Cirugía de luxación patelar');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (5, 'Cirugía de cuerpo extraño gastrointestinal');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (6, 'Cesárea en perra');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (7, 'Cesárea en gata');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (8, 'Cirugía de vejiga urinaria');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (9, 'Cirugía de glándulas anales');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (10, 'Amputación de extremidad');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (11, 'Remoción de tumor cutáneo');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (12, 'Cirugía ortopédica por fractura');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (13, 'Corrección de entropión');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (14, 'Cirugía de hernia umbilical');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (15, 'Cirugía de hernia inguinal');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (16, 'Enucleación ocular');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (17, 'Cirugía de otohematoma');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (18, 'Ablación total del canal auditivo');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (19, 'Cirugía de paladar hendido');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (20, 'Cirugía de fístula perianal');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (21, 'Biopsia quirúrgica');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (22, 'Cirugía laparoscópica exploratoria');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (23, 'Cirugía de tiroides');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (24, 'Cirugía de bazo (esplenectomía)');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (25, 'Cirugía de laringe');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (26, 'Cirugía para torsión gástrica');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (27, 'Corrección de prolapso rectal');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (28, 'Corrección de prolapso vaginal');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (29, 'Cirugía de nódulo mamario');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (30, 'Cirugía de parálisis laríngea');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (31, 'Corrección de displasia de cadera');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (32, 'Fijación de fracturas óseas');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (33, 'Orquiectomía en conejo');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (34, 'Ovariohisterectomía en conejo');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (35, 'Extracción de espolones en aves');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (36, 'Cirugía de quiste ovárico en cobayo');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (37, 'Cirugía de vejiga en hurón');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (38, 'Corrección de fractura en iguana');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (39, 'Cirugía ocular en tortuga');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (40, 'Extracción de huevo retenido (ave)');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (41, 'Extracción de tumor subcutáneo (hamster)');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (42, 'Castración en hurón');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (43, 'Cierre de heridas profundas');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (44, 'Cirugía bucal (limpieza y extracción)');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (45, 'Corrección de maloclusión dental');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (46, 'Corrección de absceso subcutáneo');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (47, 'Cirugía de vejiga por cálculos');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (48, 'Cirugía de médula espinal');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (49, 'Implante de chip subcutáneo');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (50, 'Extracción de espina clavada');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (51, 'Corrección de fisura nasal');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (52, 'Cirugía cardíaca menor');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (53, 'Cirugía en vejiga obstruida (gato)');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (54, 'Desbridamiento de tejido necrótico');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (55, 'Cirugía en pez por tumor externo');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (56, 'Corrección de prolapsos cloacales (ave)');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (57, 'Extracción de parásitos subcutáneos');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (58, 'Cirugía reconstructiva tras accidente');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (59, 'Cirugía articular');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (60, 'Cirugía gastrointestinal (hurón)');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (61, 'Apertura de absceso ocular');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (62, 'Resección intestinal');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (63, 'Colocación de sonda esofágica');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (64, 'Resección de masa abdominal');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (65, 'Reducción de fractura mandibular');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (66, 'Cirugía de próstata');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (67, 'Fijación de luxación de hombro');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (68, 'Extirpación de masa hepática');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (69, 'Cirugía en aleta dañada (pez)');
INSERT INTO veterinariaTX.dbo.TIPO_CIRUGIA (ID_TIPO_CIRUGIA, NOMBRE_CIRUGIA) VALUES (70, 'Cirugía en caparazón de tortuga');