INSERT INTO veterinariaTX.dbo.provincia(NOMBRE_PROVINCIA, ID_DIRECCION_PROVINCIA) values ('Alajuela',2);
INSERT INTO veterinariaTX.dbo.provincia(NOMBRE_PROVINCIA, ID_DIRECCION_PROVINCIA) values ('Cartago',3);
INSERT INTO veterinariaTX.dbo.provincia(NOMBRE_PROVINCIA, ID_DIRECCION_PROVINCIA) values ('Guanacaste',5);
INSERT INTO veterinariaTX.dbo.provincia(NOMBRE_PROVINCIA, ID_DIRECCION_PROVINCIA) values ('Heredia',4);
INSERT INTO veterinariaTX.dbo.provincia(NOMBRE_PROVINCIA, ID_DIRECCION_PROVINCIA) values ('Limón',7);
INSERT INTO veterinariaTX.dbo.provincia(NOMBRE_PROVINCIA, ID_DIRECCION_PROVINCIA) values ('Puntarenas',6);
INSERT INTO veterinariaTX.dbo.provincia(NOMBRE_PROVINCIA, ID_DIRECCION_PROVINCIA) values ('San José',1);

INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Alajuela',2,21);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Atenas',2,25);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Grecia',2,23);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Guatuso',2,215);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Los Chiles',2,214);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Naranjo',2,26);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Orotina',2,29);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Palmares',2,27);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Poás',2,28);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Río Cuarto',2,216);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('San Carlos',2,210);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('San Mateo',2,24);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('San Ramón',2,22);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Sarchí',2,212);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Upala',2,213);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Zarcero',2,211);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Alvarado',3,36);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Cartago',3,31);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('El Guarco',3,38);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Jiménez',3,34);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('La Unión',3,33);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Oreamuno',3,37);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Paraíso',3,32);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Turrialba',3,35);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Abangares',5,57);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Bagaces',5,54);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Cañas',5,56);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Carrillo',5,55);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Hojancha',5,511);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('La Cruz',5,510);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Liberia',5,51);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Nandayure',5,59);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Nicoya',5,52);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Santa Cruz',5,53);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Tilarán',5,58);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Barva',4,42);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Belén',4,47);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Flores',4,48);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Heredia',4,41);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('San Isidro',4,46);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('San Pablo',4,49);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('San Rafael',4,45);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Santa Bárbara',4,44);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Santo Domingo',4,43);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Sarapiquí',4,410);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Guácimo',7,76);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Limón',7,71);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Matina',7,75);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Pococí',7,72);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Siquirres',7,73);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Talamanca',7,74);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Buenos Aires',6,63);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Corredores',6,610);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Coto Brus',6,68);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Esparza',6,62);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Garabito',6,611);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Golfito',6,67);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Montes de Oro',6,64);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Osa',6,65);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Parrita',6,69);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Puntarenas',6,61);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Quepos',6,66);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Acosta',1,112);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Alajuelita',1,110);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Aserrí',1,16);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Curridabat',1,118);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Desamparados',1,13);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Dota',1,117);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Escazú',1,12);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Goicoechea',1,18);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('León Cortés Castro',1,120);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Montes de Oca',1,115);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Mora',1,17);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Moravia',1,114);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Pérez Zeledón',1,119);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Puriscal',1,14);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('San José',1,11);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Santa Ana',1,19);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Tarrazú',1,15);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Tibás',1,113);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Turrubares',1,116);
INSERT INTO veterinariaTX.dbo.canton(NOMBRE_CANTON, PROVINCIA_ID, ID_DIRECCION_CANTON) values ('Vásquez de Coronado',1,111);

INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Alajuela',21,211);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San José',21,212);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Carrizal',21,213);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Antonio',21,214);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Guácima',21,215);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Isidro',21,216);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Sabanilla',21,217);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Rafael',21,218);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Río Segundo',21,219);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Desamparados',21,2110);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Turrúcares',21,2111);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Tambor',21,2112);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Garita',21,2113);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Sarapiquí',21,2114);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Atenas',25,251);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Jesús',25,252);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Mercedes',25,253);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Isidro',25,254);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Concepción',25,255);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San José',25,256);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Santa Eulalia',25,257);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Escobal',25,258);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Grecia',23,231);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Isidro',23,232);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San José',23,233);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Roque',23,234);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Tacares',23,235);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Puente de Piedra',23,237);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Bolívar',23,238);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Rafael',215,2151);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Buenavista',215,2152);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Cote',215,2153);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Katira',215,2154);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Los Chiles',214,2141);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Caño Negro',214,2142);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('El Amparo',214,2143);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Jorge',214,2144);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Naranjo',26,261);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Miguel',26,262);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San José',26,263);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Cirrí Sur',26,264);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Jerónimo',26,265);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Juan',26,266);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('El Rosario',26,267);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Palmitos',26,268);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Orotina',29,291);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('El Mastate',29,292);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Hacienda Vieja',29,293);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Coyolar',29,294);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('La Ceiba',29,295);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Palmares',27,271);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Zaragoza',27,272);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Buenos Aires',27,273);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Santiago',27,274);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Candelaria',27,275);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Esquipulas',27,276);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('La Granja',27,277);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Pedro',28,281);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Juan',28,282);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Rafael',28,283);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Carrillos',28,284);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Sabana Redonda',28,285);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Río Cuarto',216,2161);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Santa Rita',216,2162);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Santa Isabel',216,2163);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Quesada',210,2101);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Florencia',210,2102);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Buenavista',210,2103);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Aguas Zarcas',210,2104);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Venecia',210,2105);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Pital',210,2106);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('La Fortuna',210,2107);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('La Tigra',210,2108);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('La Palmera',210,2109);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Venado',210,21010);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Cutris',210,21011);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Monterrey',210,21012);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Pocosol',210,21013);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Mateo',24,241);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Desmonte',24,242);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Jesús María',24,243);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Labrador',24,244);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Ramón',22,221);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Santiago',22,222);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Juan',22,223);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Piedades Norte',22,224);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Piedades Sur',22,225);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Rafael',22,226);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Isidro',22,227);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Los Ángeles',22,228);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Alfaro',22,229);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Volio',22,2210);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Concepción',22,2211);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Zapotal',22,2212);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Peñas Blancas',22,2213);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Lorenzo',22,2214);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Sarchí Norte',212,2121);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Sarchí Sur',212,2122);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Toro Amarillo',212,2123);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Pedro',212,2124);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Rodríguez',212,2125);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Upala',213,2131);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Aguas Claras',213,2132);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San José o Pizote',213,2133);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Bijagua',213,2134);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Delicias',213,2135);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Dos Ríos',213,2136);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Yolillal',213,2137);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Canalete',213,2138);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Zarcero',211,2111);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Laguna',211,2112);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Tapezco',211,2113);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Guadalupe',211,2114);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Palmira',211,2115);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Zapote',211,2116);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Brisas',211,2117);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Pacayas',36,361);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Cervantes',36,362);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Capellades',36,363);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Oriental',31,311);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Occidental',31,312);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Carmen',31,313);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Nicolás',31,314);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Aguacaliente o San Francisco',31,315);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Guadalupe o Arenilla',31,316);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Corralillo',31,317);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Tierra Blanca',31,318);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Dulce Nombre',31,319);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Llano Grande',31,3110);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Quebradilla',31,3111);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Tejar',38,381);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Isidro',38,382);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Tobosi',38,383);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Patio de Agua',38,384);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Juan Viñas',34,341);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Tucurrique',34,342);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Pejibaye',34,343);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Tres Ríos',33,331);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Diego',33,332);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Juan',33,333);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Rafael',33,334);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Concepción',33,335);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Dulce Nombre',33,336);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Ramón',33,337);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Río Azul',33,338);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Rafael',37,371);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Cot',37,372);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Potrero Cerrado',37,373);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Cipreses',37,374);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Santa Rosa',37,375);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Paraíso',32,321);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Santiago',32,322);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Orosi',32,323);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Cachí',32,324);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Llanos de Santa Lucía',32,325);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Turrialba',35,351);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('La Suiza',35,352);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Peralta',35,353);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Santa Cruz',35,354);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Santa Teresita',35,355);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Pavones',35,356);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Tuis',35,357);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Tayutic',35,358);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Santa Rosa',35,359);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Tres Equis',35,3510);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('La Isabel',35,3511);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Chirripó',35,3512);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Las Juntas',57,571);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Sierra',57,572);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Juan',57,573);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Colorado',57,574);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Bagaces',54,541);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Fortuna',54,542);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Mogote',54,543);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Río Naranjo',54,544);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Cañas',56,561);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Palmira',56,562);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Miguel',56,563);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Bebedero',56,564);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Porozal',56,565);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Filadelfia',55,551);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Palmira',55,552);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Sardinal',55,553);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Belén',55,554);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Hojancha',511,5111);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Monte Romo',511,5112);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Puerto Carrillo',511,5113);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Huacas',511,5114);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Matambú',511,5115);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('La Cruz',510,5101);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Santa Cecilia',510,5102);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Garita',510,5103);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Santa Elena',510,5104);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Liberia',51,511);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Cañas Dulces',51,512);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Mayorga',51,513);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Nacascolo',51,514);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Curubandé',51,515);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Carmona',59,591);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Santa Rita',59,592);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Zapotal',59,593);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Pablo',59,594);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Porvenir',59,595);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Bejuco',59,596);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Nicoya',52,521);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Mansion',52,522);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Antonio',52,523);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Quebrada Honda',52,524);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Samara',52,525);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Nosara',52,526);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Belén de Nosarita',52,527);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Santa Cruz',53,531);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Bolsón',53,532);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Veintisiete de Abril',53,533);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Tempate',53,534);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Cartagena',53,535);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Cuajiniquil',53,536);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Diria',53,537);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Cabo Velas',53,538);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Tamarindo',53,539);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Tilarán',58,581);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Quebrada Grande',58,582);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Tronadora',58,583);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Santa Rosa',58,584);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Líbano',58,585);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Tierras Morenas',58,586);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Arenal',58,587);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Barva',42,421);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Pedro',42,422);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Pablo',42,423);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Roque',42,424);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Santa Lucía',42,425);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San José de la Montaña',42,426);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Antonio',47,471);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Rivera',47,472);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('La Asunción',47,473);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Joaquín',48,481);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Barrantes',48,482);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Llorente',48,483);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Heredia',41,411);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Mercedes',41,412);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Francisco',41,413);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Ulloa',41,414);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Varablanca',41,415);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Isidro',46,461);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San José',46,462);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Concepción',46,463);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Francisco',46,464);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Pablo',49,491);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Rincón de Sabanilla',49,492);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Rafael',45,451);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Josecito',45,452);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Santiago',45,453);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Angeles',45,454);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Concepción',45,455);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Santa Bárbara',44,441);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Pedro',44,442);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Juan',44,443);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Jesús',44,444);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Santo Domingo',44,445);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Purabá',44,446);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Santo Domingo',43,431);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Vicente',43,432);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Miguel',43,433);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Paracito',43,434);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Santo Tomás',43,435);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Santa Rosa',43,436);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Tures',43,437);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Pará',43,438);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Puerto Viejo',410,4101);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('La Virgen',410,4102);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Horquetas',410,4103);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Llanuras del Gaspar',410,4104);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Cureña',410,4105);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Guácimo',76,761);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Mercedes',76,762);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Pocora',76,763);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Río Jiménez',76,764);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Duacarí',76,765);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Limón',71,711);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Valle La Estrella',71,712);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Río Blanco',71,713);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Matama',71,714);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Matina',75,751);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Batán',75,752);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Carrandi',75,753);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Guápiles',72,721);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Jiménez',72,722);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('La Rita',72,723);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Roxana',72,724);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Cariari',72,725);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Colorado',72,726);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('La Colonia',72,727);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Siquirres',73,731);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Pacuarito',73,732);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Florida',73,733);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Germania',73,734);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Cairo',73,735);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Alegría',73,736);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Bratsi',74,741);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Sixaola',74,742);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Cahuita',74,743);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Telire',74,744);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Buenos Aires',63,631);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Volcan',63,632);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Potrero Grande',63,633);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Boruca',63,634);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Pilas',63,635);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Colinas',63,636);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Changena',63,637);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Briolley',63,638);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Brunka',63,639);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Corredor',610,6101);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('La Cuesta',610,6102);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Canoas',610,6103);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Laurel',610,6104);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Vito',68,681);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Sabalito',68,682);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Aguabuena',68,683);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Limóncito',68,684);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Pittier',68,685);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Gutiérrez Braun',68,686);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Espíritu Santo',62,621);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Juan Grande',62,622);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Macacona',62,623);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Rafael',62,624);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Jerónimo',62,625);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Caldera',62,626);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Jacó',611,6111);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Tarcoles',611,6112);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Golfito',67,671);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Puerto Jiménez',67,672);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Guaycará',67,673);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Pavón',67,674);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Miramar',64,641);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('La Unión',64,642);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Isidro',64,643);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Puerto Cortés',65,651);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Palmar',65,652);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Sierpe',65,653);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Bahia Ballena',65,654);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Piedras Blancas',65,655);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Bahía Drake',65,656);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Parrita',69,691);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Puntarenas',61,611);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Pitahaya',61,612);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Chomes',61,613);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Lepanto',61,614);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Paquera',61,615);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Manzanillo',61,616);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Guacimal',61,617);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Barranca',61,618);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Monte Verde',61,619);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Isla del Coco',61,6110);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Cobano',61,6111);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Chacarita',61,6112);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Chira',61,6113);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Acapulco',61,6114);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('El Roble',61,6115);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Arancibia',61,6116);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Quepos',66,661);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Savegre',66,662);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Naranjito',66,663);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Ignacio',112,1121);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Guaitil',112,1122);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Palmichal',112,1123);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Cangrejal',112,1124);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Sabanillas',112,1125);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Alajuelita',110,1101);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Josecito',110,1102);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Antonio',110,1103);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Concepción',110,1104);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Felipe',110,1105);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Aserrí',16,161);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Tarbaca',16,162);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Vuelta de Jorco',16,163);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Gabriel',16,164);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Legua',16,165);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Monterrey',16,166);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Salitrillos',16,167);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Curridabat',118,1181);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Granadilla',118,1182);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Sánchez',118,1183);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Tirrases',118,1184);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Desamparados',13,131);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Miguel',13,132);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Juan de Dios',13,133);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Rafael Arriba',13,134);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Antonio',13,135);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Frailes',13,136);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Patarrá',13,137);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Cristóbal',13,138);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Rosario',13,139);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Damas',13,1310);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Rafael Abajo',13,1311);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Gravilias',13,1312);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Los Guido',13,1313);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Santa María',117,1171);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Jardín',117,1172);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Copey',117,1173);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Escazú',12,121);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Antonio',12,122);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Rafael',12,123);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Guadalupe',18,181);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Francisco',18,182);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Calle Blancos',18,183);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Mata de Plátano',18,184);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Ipís',18,185);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Rancho Redondo',18,186);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Purral',18,187);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Pablo',120,1201);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Andrés',120,1202);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Llano Bonito',120,1203);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Isidro',120,1204);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Santa Cruz',120,1205);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Antonio',120,1206);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Pedro',115,1151);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Sabanilla',115,1152);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Mercedes',115,1153);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Rafael',115,1154);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Colón',17,171);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Guayabo',17,172);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Tabarcia',17,173);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Piedras Negras',17,174);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Picagres',17,175);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Jaris',17,176);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Quitirrisí',17,177);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Vicente',114,1141);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Jerónimo',114,1142);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('La Trinidad',114,1143);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Isidro de El General',119,1191);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('El General',119,1192);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Daniel Flores',119,1193);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Rivas',119,1194);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Pedro',119,1195);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Platanares',119,1196);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Pejibaye',119,1197);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Cajón',119,1198);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Barú',119,1199);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Río Nuevo',119,11910);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Páramo',119,11911);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('La Amistad',119,11912);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Santiago',14,141);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Mercedes Sur',14,142);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Barbacoas',14,143);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Grifo Alto',14,144);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Rafael',14,145);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Candelarita',14,146);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Desamparaditos',14,147);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Antonio',14,148);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Chires',14,149);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Carmen',11,111);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Merced',11,112);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Hospital',11,113);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Catedral',11,114);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Zapote',11,115);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Francisco de Dos Ríos',11,116);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Uruca',11,117);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Mata Redonda',11,118);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Pavas',11,119);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Hatillo',11,1110);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Sebastián',11,1111);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Santa Ana',19,191);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Salitral',19,192);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Pozos',19,193);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Uruca',19,194);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Piedades',19,195);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Brasil',19,196);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Marcos',15,151);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Lorenzo',15,152);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Carlos',15,153);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Juan',113,1131);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Cinco Esquinas',113,1132);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Anselmo Llorente',113,1133);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('León XIII',113,1134);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Colima',113,1135);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Pablo',116,1161);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Pedro',116,1162);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Juan de Mata',116,1163);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Luis',116,1164);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Carara',116,1165);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Isidro',111,1111);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('San Rafael',111,1112);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Dulce Nombre de Jesús',111,1113);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Patalillo',111,1114);
INSERT INTO veterinariaTX.dbo.distritos(NOMBRE_DISTRITO, CANTON_ID, ID_DIRECCION_DISTRITO) values ('Cascajal',111,1115);
