INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (1, 'Labrador Retriever', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (2, 'Bulldog', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (3, 'Golden Retriever', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (4, 'Beagle', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (5, 'Poodle', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (6, 'Rottweiler', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (7, 'Yorkshire Terrier', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (8, 'Boxer', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (9, 'Dachshund', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (10, 'Siberian Husky', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (11, 'Chihuahua', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (12, 'Great Dane', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (13, 'Doberman', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (14, 'Australian Shepherd', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (15, 'Shih Tzu', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (16, 'Cocker Spaniel', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (17, 'Border Collie', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (18, 'Bichon Frise', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (19, 'Boston Terrier', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (20, 'Pug', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (21, 'Maltese', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (22, 'French Bulldog', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (23, 'Pomeranian', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (24, 'English Bulldog', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (25, 'Akita', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (26, 'Newfoundland', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (27, 'Weimaraner', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (28, 'Collie', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (29, 'Papillon', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (30, 'St. Bernard', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (31, 'Cairn Terrier', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (32, 'Bull Terrier', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (33, 'Bloodhound', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (34, 'Basset Hound', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (35, 'Alaskan Malamute', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (36, 'Samoyed', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (37, 'Whippet', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (38, 'Lhasa Apso', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (39, 'German Shepherd', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (40, 'Irish Setter', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (41, 'Airedale Terrier', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (42, 'Basenji', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (43, 'Belgian Malinois', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (44, 'Bernese Mountain Dog', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (45, 'Bluetick Coonhound', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (46, 'Borzoi', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (47, 'Brussels Griffon', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (48, 'Catahoula Leopard Dog', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (49, 'Cavalier King Charles Spaniel', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (50, 'Chesapeake Bay Retriever', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (51, 'Chinese Crested', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (52, 'Clumber Spaniel', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (53, 'Dandie Dinmont Terrier', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (54, 'English Coonhound', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (55, 'English Foxhound', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (56, 'English Setter', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (57, 'Entlebucher Mountain Dog', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (58, 'Field Spaniel', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (59, 'Finnish Spitz', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (60, 'Flat-Coated Retriever', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (61, 'German Pinscher', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (62, 'German Shorthaired Pointer', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (63, 'Giant Schnauzer', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (64, 'Glen of Imaal Terrier', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (65, 'Goldador', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (66, 'Gordon Setter', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (67, 'Great Pyrenees', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (68, 'Greyhound', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (69, 'Harrier', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (70, 'Havanese', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (71, 'Ibizan Hound', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (72, 'Icelandic Sheepdog', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (73, 'Irish Terrier', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (74, 'Irish Water Spaniel', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (75, 'Irish Wolfhound', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (76, 'Italian Greyhound', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (77, 'Japanese Chin', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (78, 'Keeshond', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (79, 'Kerry Blue Terrier', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (80, 'Komondor', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (81, 'Kooikerhondje', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (82, 'Kuvasz', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (83, 'Labradoodle', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (84, 'Lakeland Terrier', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (85, 'Leonberger', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (86, 'Lowchen', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (87, 'Maltipoo', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (88, 'Manchester Terrier', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (89, 'Miniature Bull Terrier', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (90, 'Miniature Pinscher', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (91, 'Miniature Schnauzer', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (92, 'Neapolitan Mastiff', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (93, 'Norfolk Terrier', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (94, 'Norwegian Buhund', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (95, 'Norwegian Elkhound', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (96, 'Norwegian Lundehund', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (97, 'Norwich Terrier', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (98, 'Nova Scotia Duck Tolling Retriever', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (99, 'Old English Sheepdog', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (100, 'Otterhound', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (101, 'Parson Russell Terrier', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (102, 'Pekingese', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (103, 'Pembroke Welsh Corgi', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (104, 'Perro de Agua Español', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (105, 'Petit Basset Griffon Vendeen', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (106, 'Pharaoh Hound', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (107, 'Plott', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (108, 'Pointer', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (109, 'Polish Lowland Sheepdog', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (110, 'Portuguese Water Dog', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (111, 'Presa Canario', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (112, 'Puli', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (113, 'Pumi', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (114, 'Rat Terrier', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (115, 'Redbone Coonhound', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (116, 'Rhodesian Ridgeback', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (117, 'Saluki', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (118, 'Schipperke', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (119, 'Scottish Deerhound', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (120, 'Scottish Terrier', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (121, 'Sealyham Terrier', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (122, 'Shetland Sheepdog', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (123, 'Shiba Inu', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (124, 'Silky Terrier', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (125, 'Skye Terrier', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (126, 'Sloughi', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (127, 'Soft Coated Wheaten Terrier', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (128, 'Spanish Mastiff', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (129, 'Spinone Italiano', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (130, 'Staffordshire Bull Terrier', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (131, 'Standard Schnauzer', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (132, 'Sussex Spaniel', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (133, 'Swedish Vallhund', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (134, 'Tibetan Mastiff', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (135, 'Tibetan Spaniel', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (136, 'Tibetan Terrier', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (137, 'Toy Fox Terrier', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (138, 'Treeing Walker Coonhound', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (139, 'Vizsla', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (140, 'Volpino Italiano', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (141, 'Weimaraner', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (142, 'Welsh Springer Spaniel', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (143, 'Welsh Terrier', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (144, 'West Highland White Terrier', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (145, 'Wheaten Terrier', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (146, 'Wire Fox Terrier', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (147, 'Xoloitzcuintli', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (148, 'Yorkipoo', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (149, 'American Eskimo Dog', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (150, 'American Foxhound', 1);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (151, 'Persa', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (152, 'Maine Coon', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (153, 'Siamés', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (154, 'Ragdoll', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (155, 'Bengala', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (156, 'Abisinio', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (157, 'Exótico de pelo corto', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (158, 'Bosque de Noruega', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (159, 'Siberiano', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (160, 'British Shorthair', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (161, 'Sphynx', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (162, 'Burmés', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (163, 'Cornish Rex', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (164, 'Oriental', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (165, 'Scottish Fold', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (166, 'Manx', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (167, 'Devon Rex', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (168, 'Tonkinés', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (169, 'Himalayo', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (170, 'Azul Ruso', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (171, 'American Shorthair', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (172, 'Singapura', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (173, 'Chartreux', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (174, 'Balines', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (175, 'Toyger', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (176, 'Savannah', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (177, 'Ocicat', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (178, 'LaPerm', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (179, 'Turkish Angora', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (180, 'Selkirk Rex', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (181, 'Burmilla', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (182, 'Bombay', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (183, 'Korat', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (184, 'Japanese Bobtail', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (185, 'American Curl', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (186, 'Turkish Van', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (187, 'Peterbald', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (188, 'Ragamuffin', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (189, 'Pixie Bob', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (190, 'Nebelung', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (191, 'Oriental de pelo largo', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (192, 'Munchkin', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (193, 'Cymric', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (194, 'Cheetoh', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (195, 'Foldex', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (196, 'Khao Manee', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (197, 'Chantilly-Tiffany', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (198, 'Havana Brown', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (199, 'Lykoi', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (200, 'Minuet', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (201, 'Dwelf', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (202, 'American Wirehair', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (203, 'California Spangled', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (204, 'Javanese', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (205, 'Thai', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (206, 'Serengeti', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (207, 'Tiffanie', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (208, 'Ural Rex', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (209, 'York Chocolate', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (210, 'Asian Semi-longhair', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (211, 'Persa 1', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (212, 'Maine Coon 2', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (213, 'Siamés 3', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (214, 'Ragdoll 4', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (215, 'Bengala 5', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (216, 'Abisinio 6', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (217, 'Exótico de pelo corto 7', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (218, 'Bosque de Noruega 8', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (219, 'Siberiano 9', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (220, 'British Shorthair 10', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (221, 'Sphynx 11', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (222, 'Burmés 12', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (223, 'Cornish Rex 13', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (224, 'Oriental 14', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (225, 'Scottish Fold 15', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (226, 'Manx 16', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (227, 'Devon Rex 17', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (228, 'Tonkinés 18', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (229, 'Himalayo 19', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (230, 'Azul Ruso 20', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (231, 'American Shorthair 21', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (232, 'Singapura 22', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (233, 'Chartreux 23', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (234, 'Balines 24', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (235, 'Toyger 25', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (236, 'Savannah 26', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (237, 'Ocicat 27', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (238, 'LaPerm 28', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (239, 'Turkish Angora 29', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (240, 'Selkirk Rex 30', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (241, 'Burmilla 31', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (242, 'Bombay 32', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (243, 'Korat 33', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (244, 'Japanese Bobtail 34', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (245, 'American Curl 35', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (246, 'Turkish Van 36', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (247, 'Peterbald 37', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (248, 'Ragamuffin 38', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (249, 'Pixie Bob 39', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (250, 'Nebelung 40', 2);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (251, 'Periquito', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (252, 'Canario', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (253, 'Cacatúa', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (254, 'Loro Amazona', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (255, 'Guacamayo', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (256, 'Agapornis', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (257, 'Ninfa', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (258, 'Cotorra Argentina', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (259, 'Jilguero', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (260, 'Diamante Mandarín', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (261, 'Tucán', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (262, 'Pionus', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (263, 'Lori', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (264, 'Turaco', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (265, 'Cálao', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (266, 'Yaco', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (267, 'Loro Eclectus', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (268, 'Conuro del sol', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (269, 'Cacatúa Ninfa', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (270, 'Perico Australiano', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (271, 'Loro Senegalés', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (272, 'Cacatúa Galah', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (273, 'Amazona Frentiazul', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (274, 'Agapornis Roseicollis', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (275, 'Loro del Cabo', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (276, 'Kakariki', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (277, 'Aratinga', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (278, 'Cacatúa Alba', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (279, 'Cacatúa Inca', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (280, 'Perico de Bourke', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (281, 'Perico de collar', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (282, 'Agapornis Fischeri', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (283, 'Agapornis Personata', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (284, 'Loro Cabeza Azul', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (285, 'Loro Arcoíris', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (286, 'Loro de Jardine', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (287, 'Loro de Meyer', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (288, 'Loro Pionus', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (289, 'Guacamayo Azulamarillo', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (290, 'Guacamayo Rojo', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (291, 'Guacamayo Verde', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (292, 'Cacatúa de moño amarillo', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (293, 'Canario Roller', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (294, 'Canario Gloster', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (295, 'Periquito Inglés', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (296, 'Periquito Holandés', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (297, 'Cacatúa Rosada', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (298, 'Loro Nanday', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (299, 'Loro Patagónico', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (300, 'Amazona Vinacea', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (301, 'Guacamayo Enano', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (302, 'Perico Celestial', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (303, 'Perico Cabeza de Ciruela', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (304, 'Periquito de Alas Verdes', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (305, 'Lori Arcoiris', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (306, 'Perico Esmeralda', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (307, 'Periquito de Rabadilla Roja', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (308, 'Agapornis Taranta', 3);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (309, 'Enano Holandés', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (310, 'Cabeza de León', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (311, 'Mini Rex', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (312, 'Mini Lop', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (313, 'Hotot', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (314, 'Californiano', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (315, 'Angora', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (316, 'Rex', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (317, 'Flemish Giant', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (318, 'Holland Lop', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (319, 'Britannia Petite', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (320, 'English Lop', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (321, 'American Fuzzy Lop', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (322, 'Netherland Dwarf', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (323, 'English Spot', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (324, 'French Lop', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (325, 'Tan', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (326, 'Himalayan', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (327, 'Chinchilla', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (328, 'Polish', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (329, 'Thrianta', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (330, 'Belgian Hare', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (331, 'Silver Marten', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (332, 'Dwarf Hotot', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (333, 'Blanc de Hotot', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (334, 'English Angora', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (335, 'French Angora', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (336, 'Giant Angora', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (337, 'Satin Angora', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (338, 'American Sable', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (339, 'Checkered Giant', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (340, 'Cinnamon', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (341, 'Creme d’Argent', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (342, 'Florida White', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (343, 'Harlequin', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (344, 'Lilac', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (345, 'Palomino', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (346, 'Rhinelander', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (347, 'Satin', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (348, 'Silver', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (349, 'Silver Fox', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (350, 'Standard Chinchilla', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (351, 'American Chinchilla', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (352, 'Beige', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (353, 'Beveren', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (354, 'Argente Brun', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (355, 'Vienna Blue', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (356, 'Dutch', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (357, 'Velveteen Lop', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (358, 'Plush Lop', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (359, 'Mini Satin', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (360, 'Broken Mini Rex', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (361, 'Tri-Color Dutch', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (362, 'Spotted Mini Lop', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (363, 'Black Otter Rex', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (364, 'Chestnut Netherland Dwarf', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (365, 'Agouti Lop', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (366, 'Blue Havana', 4);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (367, 'Hamster Sirio', 5);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (368, 'Hamster Dorado', 5);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (369, 'Hamster Enano Ruso', 5);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (370, 'Hamster Enano Campbell', 5);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (371, 'Hamster Enano Roborovski', 5);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (372, 'Hamster Chino', 5);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (373, 'Hamster Albino', 5);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (374, 'Hamster Panda', 5);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (375, 'Hamster de Pelo Largo', 5);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (376, 'Hamster de Pelo Corto', 5);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (377, 'Hamster Satinado', 5);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (378, 'Hamster Tortuga', 5);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (379, 'Hamster Arlequín', 5);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (380, 'Hamster Tricolor', 5);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (381, 'Hamster de Invierno', 5);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (382, 'Hamster Negro', 5);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (383, 'Hamster Beige', 5);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (384, 'Hamster Gris', 5);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (385, 'Hamster Blanco', 5);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (386, 'Hamster Canela', 5);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (387, 'Tortuga de Orejas Rojas', 6);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (388, 'Tortuga de Caja', 6);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (389, 'Tortuga Rusa', 6);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (390, 'Tortuga Sulcata', 6);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (391, 'Tortuga Leopardo', 6);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (392, 'Tortuga de Espolones', 6);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (393, 'Tortuga Estrellada India', 6);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (394, 'Tortuga de Madera', 6);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (395, 'Tortuga de Caparazón Blando', 6);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (396, 'Tortuga Mediterránea', 6);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (397, 'Tortuga de Florida', 6);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (398, 'Tortuga Aldabra', 6);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (399, 'Tortuga de Galápagos', 6);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (400, 'Tortuga Mora', 6);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (401, 'Tortuga Pintada', 6);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (402, 'Tortuga del Desierto', 6);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (403, 'Tortuga Matamata', 6);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (404, 'Tortuga Moteada', 6);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (405, 'Tortuga Almizclera', 6);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (406, 'Tortuga de Pantano', 6);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (407, 'Iguana Verde', 7);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (408, 'Iguana Azul', 7);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (409, 'Iguana Roja', 7);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (410, 'Iguana Rinoceronte', 7);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (411, 'Iguana del Desierto', 7);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (412, 'Iguana Marina', 7);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (413, 'Iguana de Fiyi', 7);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (414, 'Iguana Enana de Jamaica', 7);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (415, 'Iguana Rayada', 7);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (416, 'Iguana de Ctenosaura', 7);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (417, 'Hurón Estándar', 8);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (418, 'Hurón Albino', 8);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (419, 'Hurón Plateado', 8);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (420, 'Hurón Canela', 8);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (421, 'Hurón Chocolate', 8);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (422, 'Hurón Negro', 8);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (423, 'Hurón Panda', 8);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (424, 'Hurón Siamés', 8);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (425, 'Hurón Blanco de Ojos Negros', 8);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (426, 'Hurón Champagne', 8);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (427, 'Cobayo Abisinio', 9);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (428, 'Cobayo Americano', 9);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (429, 'Cobayo Peruano', 9);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (430, 'Cobayo Silkie', 9);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (431, 'Cobayo Coronet', 9);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (432, 'Cobayo Teddy', 9);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (433, 'Cobayo Texel', 9);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (434, 'Cobayo Skinny', 9);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (435, 'Cobayo Baldwin', 9);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (436, 'Cobayo Rex', 9);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (437, 'Pez Betta', 10);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (438, 'Pez Guppy', 10);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (439, 'Pez Neon', 10);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (440, 'Pez Ángel', 10);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (441, 'Pez Disco', 10);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (442, 'Pez Oscar', 10);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (443, 'Pez Molly', 10);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (444, 'Pez Platy', 10);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (445, 'Pez Koi', 10);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (446, 'Pez Dorado', 10);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (447, 'Pez Cebra', 10);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (448, 'Pez Espada', 10);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (449, 'Pez Gourami', 10);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (450, 'Pez Ramirezi', 10);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (451, 'Pez Tetra Limón', 10);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (452, 'Pez Barbo Tigre', 10);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (453, 'Pez Corydora', 10);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (454, 'Pez Pleco', 10);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (455, 'Pez Danio', 10);
INSERT INTO veterinariaTX.dbo.mascota_raza (id_mascota_raza, nombre_raza, id_mascota_especie) VALUES (456, 'Pez Arlequín', 10);