-- -----------------------------------------------------
-- CREACION DE TABLAS
-- -----------------------------------------------------

create table veterinariaTX.dbo.provincia(
	ID_DIRECCION_PROVINCIA int primary key,
	NOMBRE_PROVINCIA nvarchar(45))

create table veterinariaTX.dbo.canton(
	ID_DIRECCION_CANTON int primary key,
	NOMBRE_CANTON nvarchar(50),
	PROVINCIA_ID int references veterinariaTX.dbo.provincia)

create table veterinariaTX.dbo.distritos(
	ID_DIRECCION_DISTRITO int primary key,
	NOMBRE_DISTRITO nvarchar(50),
	CANTON_ID int references veterinariaTX.dbo.canton)

create table veterinariaTX.dbo.clientes(
	ID_CLIENTES INT PRIMARY KEY,
	NOMBRE_CLIENTE NVARCHAR(45),
	TELEFONO_CLIENTE NVARCHAR(10),
	DISTRITO_ID INT REFERENCES VETERINARIATX.DBO.DISTRITOS
)


create table veterinariaTX.dbo.mascota_especie(
	ID_MASCOTA_ESPECIE INT PRIMARY KEY,
	DESCRIPCION_ESPECIE NVARCHAR(45)
)

create table veterinariaTX.dbo.mascota_raza(
	ID_MASCOTA_RAZA INT PRIMARY KEY,
	NOMBRE_RAZA NVARCHAR(45),
	ID_MASCOTA_ESPECIE INT REFERENCES VETERINARIATX.DBO.mascota_especie
)

create table veterinariaTX.dbo.mascotas(
	ID_MASCOTA INT PRIMARY KEY,
	MASCOTA_NOMBRE NVARCHAR(45),
	MASCOTA_FECHA_NACIMIENTO DATETIME,
	ID_CLIENTE INT REFERENCES VETERINARIATX.DBO.CLIENTES,
	ID_MASCOTA_RAZA INT REFERENCES VETERINARIATX.DBO.MASCOTA_RAZA
)

CREATE TABLE VETERINARIATX.DBO.CONSULTA_MOTIVO(
	ID_CONSULTA_MOTIVO INT PRIMARY KEY,
	DESCRIPCION_MOTIVO NVARCHAR(45)
)

CREATE TABLE VETERINARIATX.DBO.CONSULTAS(
	ID_CONSULTA INT PRIMARY KEY,
	FECHA_CONSULTA DATETIME,
	MONTO DECIMAL(10,2),
	ID_MOTIVO INT REFERENCES VETERINARIATX.DBO.CONSULTA_MOTIVO,
	ID_MASCOTA INT REFERENCES VETERINARIATX.DBO.MASCOTAS
)

CREATE TABLE VETERINARIATX.DBO.CIRUGIAS_PERSONAL(
	ID_CIRUGIAS_PERSONAL INT PRIMARY KEY,
	ID_USUARIO INT
)


CREATE TABLE veterinariaTX.dbo.TIPO_CIRUGIA (
    ID_TIPO_CIRUGIA INT PRIMARY KEY,
    NOMBRE_CIRUGIA NVARCHAR(100)
);

CREATE TABLE VETERINARIATX.DBO.CIRUGIAS(
	ID_CIRUGIA INT PRIMARY KEY,
	FECHA_CIRUGIA DATETIME,
	MONTO DECIMAL(10,2),
	DURACION DECIMAL,
	ID_MASCOTA INT REFERENCES VETERINARIATX.DBO.MASCOTAS,
	ID_PERSONAL INT REFERENCES VETERINARIATX.DBO.CIRUGIAS_PERSONAL,
	ID_TIPO_CIRUGIA INT REFERENCES VETERINARIATX.DBO.TIPO_CIRUGIA
)

CREATE TABLE VETERINARIATX.DBO.TIPO_PRODUCTO(
	ID_TIPO_PRODUCTO INT PRIMARY KEY,
	NOMBRE_TIPO VARCHAR(45),
)

CREATE TABLE VETERINARIATX.DBO.MARCA_PRODUCTO(
	ID_MARCA_PRODUCTO_PRODUCTO_PRODUCTO INT PRIMARY KEY,
	NOMBRE_MARCA VARCHAR(45),
)

CREATE TABLE VETERINARIATX.DBO.PRODUCTOS(
	ID_PRODUCTO INT PRIMARY KEY,
	PRODUCTO_NOMBRE VARCHAR(45),
	PRODUCTO_DESCR VARCHAR(45),
	PRODUCTO_PRECIO DECIMAL(10,2),
	PRODUCTO_STOCK INT,
    ID_MARCA_PRODUCTO_PRODUCTO_PRODUCTO INT FOREIGN KEY REFERENCES veterinariaTX.dbo.MARCA_PRODUCTO,
	ID_TIPO_PRODUCTO INT FOREIGN KEY REFERENCES veterinariaTX.dbo.TIPO_PRODUCTO,
)

CREATE TABLE VETERINARIATX.DBO.CIRUGIAS_MEDICAMENTOS(
	ID_CIRUGIAS_MEDICAMENTOS INT PRIMARY KEY,
	ID_PRODUCTOS INT REFERENCES VETERINARIATX.DBO.PRODUCTOS,
	ID_CIRUGIA INT REFERENCES VETERINARIATX.DBO.CIRUGIAS
)

CREATE TABLE VETERINARIATX.DBO.FACTURA(
	ID_FACTURA INT PRIMARY KEY,
	MONTO_TOTAL DECIMAL(10,2),
	FECHA_FACTURA DATETIME
)

CREATE TABLE VETERINARIATX.DBO.DETALLE_FACTURA(
	ID_DETALLE_FACTURA INT PRIMARY KEY,
	ID_FACTURA INT REFERENCES VETERINARIATX.DBO.FACTURA,
	ID_CONSULTA INT REFERENCES VETERINARIATX.DBO.CONSULTAS,
	CANTIDAD INT,
	ID_CIRUGIAS_MEDICAMENTOS INT REFERENCES VETERINARIATX.DBO.CIRUGIAS_MEDICAMENTOS,
	ID_PRODUCTOS INT REFERENCES VETERINARIATX.DBO.PRODUCTOS
)


--- SELECTS ---
SELECT * FROM  veterinariaTX.dbo.clientes;

SELECT * FROM  veterinariaTX.dbo.mascota_especie;
SELECT * FROM  veterinariaTX.dbo.mascota_raza;
SELECT * FROM  veterinariaTX.dbo.mascotas;

SELECT * FROM VETERINARIATX.DBO.CONSULTA_MOTIVO;
SELECT * FROM  VETERINARIATX.DBO.CONSULTAS;

SELECT * FROM  VETERINARIATX.DBO.CIRUGIAS_PERSONAL;
SELECT * FROM  VETERINARIATX.DBO.TIPO_CIRUGIA;
SELECT * FROM  VETERINARIATX.DBO.CIRUGIAS;

SELECT * FROM  VETERINARIATX.DBO.TIPO_PRODUCTO;
SELECT * FROM  VETERINARIATX.DBO.MARCA_PRODUCTO;
SELECT ID_PRODUCTO, PRODUCTO_PRECIO FROM  VETERINARIATX.DBO.PRODUCTOS;

SELECT * FROM  VETERINARIATX.DBO.CIRUGIAS_MEDICAMENTOS;

SELECT * FROM  VETERINARIATX.DBO.FACTURA;
SELECT * FROM  VETERINARIATX.DBO.DETALLE_FACTURA;

---counts por tabla---
SELECT COUNT(*) AS Total_Provincias FROM veterinariaTX.dbo.provincia;
SELECT COUNT(*) AS Total_Cantones FROM veterinariaTX.dbo.canton;
SELECT COUNT(*) AS Total_Distritos FROM veterinariaTX.dbo.distritos;
SELECT COUNT(*) AS Total_Clientes FROM veterinariaTX.dbo.clientes;

SELECT COUNT(*) AS Total_Especies FROM veterinariaTX.dbo.mascota_especie;
SELECT COUNT(*) AS Total_Razas FROM veterinariaTX.dbo.mascota_raza;
SELECT COUNT(*) AS Total_Mascotas FROM veterinariaTX.dbo.mascotas;

SELECT COUNT(*) AS Total_MotivosConsulta FROM VETERINARIATX.DBO.CONSULTA_MOTIVO;
SELECT COUNT(*) AS Total_Consultas FROM VETERINARIATX.DBO.CONSULTAS;

SELECT COUNT(*) AS Total_PersonalCirugias FROM VETERINARIATX.DBO.CIRUGIAS_PERSONAL;
SELECT COUNT(*) AS Total_TipoCirugias FROM VETERINARIATX.DBO.TIPO_CIRUGIA;
SELECT COUNT(*) AS Total_Cirugias FROM VETERINARIATX.DBO.CIRUGIAS;

SELECT COUNT(*) AS Total_TipoProducto FROM VETERINARIATX.DBO.TIPO_PRODUCTO;
SELECT COUNT(*) AS Total_MarcaProducto FROM VETERINARIATX.DBO.MARCA_PRODUCTO;
SELECT COUNT(*) AS Total_Productos FROM VETERINARIATX.DBO.PRODUCTOS;

SELECT COUNT(*) AS Total_CirugiasMedicamentos FROM VETERINARIATX.DBO.CIRUGIAS_MEDICAMENTOS;

SELECT COUNT(*) AS Total_Facturas FROM VETERINARIATX.DBO.FACTURA;
SELECT COUNT(*) AS Total_DetalleFactura FROM VETERINARIATX.DBO.DETALLE_FACTURA;



